#!/bin/bash

set -e

echo "Running Nymph Testing"
echo "Use \`run coverage\` to build coverage clover."
echo

if [[ "$1" == "coverage" ]]; then
  CVGMYSQL="--coverage-clover logs/clover-mysql.xml"
  CVGPGSQL="--coverage-clover logs/clover-pgsql.xml"
  CVGSQLITE="--coverage-clover logs/clover-sqlite.xml"
  CVG="--coverage-clover logs/clover.xml"
  shift
else
  CVGMYSQL=""
  CVGPGSQL=""
  CVGSQLITE=""
  CVG=""
fi

TESTARGS=$@

cd $(dirname $0)

if [[ "$DB" == "mysql" ]]; then
  echo "################################################################################"
  echo "#                           Running tests for MySQL                            #"
  echo -e "################################################################################\n"

  ../vendor/phpunit/phpunit/phpunit --testsuite default --bootstrap bootstrapMySQL.php $CVGMYSQL $TESTARGS
fi
if [[ "$DB" == "pgsql" ]]; then
  echo "################################################################################"
  echo "#                         Running tests for PostgreSQL                         #"
  echo -e "################################################################################\n"

  ../vendor/phpunit/phpunit/phpunit --testsuite default --bootstrap bootstrapPostgreSQL.php $CVGPGSQL $TESTARGS
fi
if [[ "$DB" == "sqlite" ]]; then
  echo "################################################################################"
  echo "#                          Running tests for SQLite3                           #"
  echo -e "################################################################################\n"

  ../vendor/phpunit/phpunit/phpunit --testsuite default --bootstrap bootstrapSQLite3.php $CVGSQLITE $TESTARGS
fi
if [[ "$DB" == "" ]]; then
  echo "################################################################################"
  echo "#                          Running tests for All DBs                           #"
  echo -e "################################################################################\n"

  DB=mysql ../vendor/phpunit/phpunit/phpunit --testsuite all-dbs --bootstrap bootstrapMySQL.php $CVG $TESTARGS
fi
